"""Prompt templates package for VirtuJudge AI-ML."""

from app.prompts.judges import (
    BANNED_REGEX,
    BANNED_SUBJECTIVE_TERMS,
    BUSINESS_STRATEGIST_PROMPT,
    COMMON_GUARDRAILS,
    PRODUCT_ANALYST_PROMPT,
    TECHNICAL_EVALUATOR_PROMPT,
)

__all__ = [
    "BANNED_REGEX",
    "BANNED_SUBJECTIVE_TERMS",
    "BUSINESS_STRATEGIST_PROMPT",
    "COMMON_GUARDRAILS",
    "PRODUCT_ANALYST_PROMPT",
    "TECHNICAL_EVALUATOR_PROMPT",
]
